# Generated by Django 4.2.11 on 2024-05-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentregipp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='username',
        ),
    ]
