# Generated by Django 4.2.11 on 2024-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregipp', '0002_remove_studentregister_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Student with this email already exists'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Student with this phone no. already exists'}, max_length=100, unique=True),
        ),
    ]
